---
title: "Variable Exploration"
author: " "
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


* * *

# First Moment

```{r}
#quiet function
quiet <- function(x) { 
  sink(tempfile()) 
  on.exit(sink()) 
  invisible(force(x)) 
}

#importing dataset
lc = read.csv("../datasets/processed/lc.csv")

#importing window
suppressMessages(library(spatstat))
suppressMessages(library(sf))
suppressMessages(library(maptools))
load("../datasets/raw/BC_Covariates.Rda")
bc_window_sf = st_as_sf(DATA$Window)
bc_window_owin = as.owin(bc_window_sf)

#converting to a ppp
lc_ppp = ppp(x = lc$decimalLongitude, 
              y = lc$decimalLatitude, 
              window = bc_window_owin, 
              )

plot(lc_ppp, pch = 16, cols = "#046C9A", cex = 0.6)
```


## Summary

```{r}
#number of observations
lc_ppp$n

#average intensity
intensity(lc_ppp)
```


## Covariates

### Elevation

```{r}
#median elevation in bc
median(DATA$Elevation)

#median elevation of lynx
median(DATA$Elevation[lc_ppp])

elecut = cut(DATA$Elevation, 5)
tab = table(elecut[lc_ppp])
nam = names(tab)
names(tab) = c("low","low-med", "medium", "med-high", "high")
tab
nam #breaks
```




### Forest Coverage

```{r}
#median forest coverage in bc
median(DATA$Forest)

#median forest coverage of lynx
median(DATA$Forest[lc_ppp])

fcut = cut(DATA$Forest, 5)
tab = table(fcut[lc_ppp])
nam = names(tab)
names(tab) = c("low","low-med", "medium", "med-high", "high")
tab
nam #breaks
```





### HFI

```{r}
#median HFI in bc
median(DATA$HFI)

#median HFI of lynx
median(DATA$HFI[lc_ppp])

hficut = cut(DATA$HFI, 5)
tab = table(hficut[lc_ppp])
nam = names(tab)
names(tab) = c("low","low-med", "medium", "med-high", "high")
tab
nam #breaks
```





### Distance to Water

```{r}
#median distance to water in bc
median(DATA$Dist_Water)

#median distance to water of lynx
median(DATA$Dist_Water[lc_ppp])

dwcut = cut(DATA$Dist_Water, 5) 
tab = table(dwcut[lc_ppp])
nam = names(tab)
names(tab) = c("low","low-med", "medium", "med-high", "high")
tab
nam #breaks
```



## Separation Distance

```{r}
m = data.frame('Separation' = nndist(lc_ppp))
marks(lc_ppp) = m

#median separation distance
median(m$Separation)

#plotting
rbPal <- colorRampPalette(c('red','blue'))
Col <- rbPal(10)[as.numeric(cut(m$Separation,breaks = 10))]
plot(lc_ppp, pch=16, cols = rbPal(nrow(m)), which.marks=NULL, main='Separation Distance')
```


## Intensity

```{r}
Q = quadratcount(lc_ppp,
                  nx = 8,
                  ny = 8)

#Plot the output 
plot(lc_ppp,
     pch = 16,
     cex = 0.5,
     cols = "#046C9A",
     main = "Lynx Locations", 
     legend = FALSE)

plot(Q, cex = 2, col = "red", add = T)

#quadrat intensity estimate
plot(intensity(Q, image = T),
     main = "Lynx intensity")

plot(lc_ppp,
     pch = 16,
     cex = 0.6,
     cols = "white",
     add = TRUE)

plot(lc_ppp,
     pch = 16,
     cex = 0.5,
     cols = "black",
     add = TRUE)

#Quadrat test of homogeneity 
quadrat.test(Q)

#hotspot analysis
#R = bw.ppl(lc_ppp)
#LR = scanLRTS(lc_ppp, r = R)
#plot(LR)
```



# Second Moment

```{r}
#Morisita's Index plot
# miplot(lc_ppp,
#        ylim = c(0,7),
#        main = "",
#        pch = 16,
#        col = "#046C9A")

#ripley's k
plot(Kest(lc_ppp),
     main = "",
     lwd = 2)

# Bootstrapped CIs
# rank = 1 means the max and min
# Border correction is to correct for edges around the window
# values will be used for CI
E_lc = envelope(lc_ppp,
                  Kest,
                  correction="border",
                  rank = 1,
                  nsim = 19,
                  fix.n = T)
plot(E_lc,
     main = "Assumed Homogeneity",
     lwd = 2)


Kinhom_lc = Kinhom(lc_ppp, density(lc_ppp, bw.ppl))
#Estimate a strictly positive density
lambda_lc_pos = density(lc_ppp,
                          sigma=bw.ppl,
                          positive=TRUE)

#Simulation envelope (with points drawn from the estimated intensity)
E_lc_inhom = quiet(envelope(lc_ppp,
                        Kinhom,
                        simulate = expression(rpoispp(lambda_lc_pos)),
                        correction="border",
                        rank = 1,
                        nsim = 19,
                        fix.n = TRUE)) #this generates warnings
plot(E_lc_inhom,
     main = "NOT Assuming Homogeneity",
     lwd = 2)


#pair correlation function
pcf_lc_inhom = suppressWarnings(quiet(envelope(lc_ppp,
                          pcfinhom,
                          simulate = expression(rpoispp(lambda_lc_pos)),
                          rank = 1,
                          nsim = 19)))
plot(pcf_lc_inhom, 
     main='NOT Assuming Homogeneity', 
     xlim=c(0, 50000))
```





